describe('Real World App', () => {
    it('Enviar - Com Saldo', () => {
    cy.visit('http://localhost:3000/')
    cy.get('#username').type('Pepe.baba')
    cy.get('#password').type('123456789@')
    cy.get('button').click()
    cy.get('.MuiListSubheader-sticky').contains('Public')
    cy.get('.MuiButton-root').click()
    cy.get('.MuiGrid-grid-xs-12')
    cy.get('[data-test="user-list-item-uBmeaz5pX"]').click()
    cy.get('.MuiContainer-maxWidthMd')
    cy.get('.MuiBox-root > .MuiGrid-container').contains('Ted Parisian')
    cy.get('#amount').type('$500')
    cy.get('#transaction-create-description-input').type('Pagamento')
    cy.get('[data-test="transaction-create-submit-payment"]').click()
    cy.get('[data-test="alert-bar-success"]')
    cy.get('.MuiContainer-maxWidthMd')
    cy.get('.MuiGrid-spacing-xs-4 > :nth-child(1) > .MuiGrid-container')
    cy.get(':nth-child(2) > .MuiGrid-container > .MuiGrid-root > .MuiTypography-root')
    cy.get('[data-test="new-transaction-return-to-transactions"]').click()
    })

    it('Enviar - Sem Saldo', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#username').type('Pepe.baba')
        cy.get('#password').type('123456789@')
        cy.get('button').click()
        cy.get('.MuiListSubheader-sticky').contains('Public')
        cy.get('.MuiButton-root').click()
        cy.get('.MuiGrid-grid-xs-12')
        cy.get('[data-test="user-list-item-uBmeaz5pX"]').click()
        cy.get('.MuiContainer-maxWidthMd')
        cy.get('.MuiBox-root > .MuiGrid-container').contains('Ted Parisian')
        cy.get('#amount').type('$10000')
        cy.get('#transaction-create-description-input').type('Pagamento')
        })

 })